## folder with prepared GDC data 
GDCdataDir: GDCdata_prepared
## script with useful functions 
utility_script: src/common_functions.R
## ensembl to hgnc mapping object
ens2hgnc: data/ens2hgnc.RDS
## cpg site to hgnc mapping object
cpg2hgnc: data/cpg2hgnc.RDS
## curated survival/clinical data
surv: data/TCGA.surv.RDS
## clinical data 
clin: data/TCGA.clin.RDS
## project dictionary (a mapping of project names to list of tcga cancer types)
projectDict: data/projects.dict.yaml
## names of genes of interest for input feature subsetting (one gene per line) 
geneset: data/hallmarks_plus_xcell.txt

# tool settings
maui:
  nfactors: 100
  epochs: 500
  threads: 3
  batch_size: 100
mofa: 
  nfactors: 100 
mcia: 
  nfactors: 20
pca: 
  nfactors: 100
RSCRIPT_EXEC: /opt/R/4.0/bin/Rscript

# how to select features 
features:
  # whether features should be only selected from the given gene sets 
  use_geneset: TRUE 
  topN: 2500 # features will be sorted by variance and top features will be selected
# folder to write the assays to 
assay_output: 
  folder: assays
  printCSV: TRUE # whether to print the assays as CSV files
  printRDS: TRUE # whether to print the assays as RDS files
pipeline_output: output
# whether to correct for batches (only applies to gene expression data)
correctBatches: FALSE 
datatypes: 
  - cnv
  - gex
  - mut
  - meth
# which file extension to use for different data types 
# gex options: gex_raw, gex.fpkm
# cnv options: 
datatype_flavors: 
  gex: gex.fpkm
  cnv: cnv_gistic 
datatype_combinations:
  - gex
  - mut
  - cnv
  - meth
  - cnv,gex,mut,meth
# path to projects dictionary
# TCGA projects with at least 100 patients with all data types (mut/gex/cnv/meth)
# at least 10 normal gex samples coming from at least two TSS
projects:
  - nsclc
  - glioma
  - TCGA-BRCA
  - pan-gastrointestinal
  - colorectal
  - pancancer
  - pan-squamous
  - pan-kidney
  - TCGA-BLCA
  - TCGA-COAD
  - TCGA-ESCA
  - TCGA-HNSC   
  - TCGA-KIRC
  - TCGA-KIRP
  - TCGA-LIHC
  - TCGA-LUAD
  - TCGA-LUSC
  - TCGA-PRAD
  - TCGA-STAD
  - TCGA-THCA
  - TCGA-UCEC
  - TCGA-CESC
  - TCGA-LGG
  - TCGA-PAAD
  - TCGA-PCPG
  - TCGA-SARC
  - TCGA-TGCT
  - TCGA-THYM
