---
title: "Manuscript Figures"
output:
  word_document: default
  html_document: default
params:
  settings_file: ''
  figures_folder: '/data/bimsbstatic/public/akalin/buyar/manuscript_figures_arcas/test'
  workdir: '.'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = params$workdir)
settings <- yaml::read_yaml(params$settings_file)
FigureFolder <- params$figures_folder
source(settings$utility_script)
library(data.table)
library(ggplot2)
library(pbapply)
library(ggrepel)
library(ggpubr)
library(cowplot)
library(ggridges)
library(ggcorrplot)
library(ComplexHeatmap)
library(pheatmap)
library(survminer)
library(survival)
theme_set(ggpubr::theme_pubclean())
geneSetScoresFolder <- '/data/local/buyar/arcas/subtyping_paper/data/geneset_scores/singscore'

inputDir <- settings$pipeline_output
assay_dir <- settings$assay_output$folder
surv <- do.call(rbind, readRDS(settings$surv))
projectDict <- sapply(yaml::read_yaml(settings$projectDict), 
                      function(x) gsub(' ', '', unlist(strsplit(x, ','))))
tcga_subtypes <- process_tcga_subtypes()

ens2hgnc <- readRDS(settings$ens2hgnc)

TOOLS <- c('maui_factors', 'mofa_factors', 'mcia_factors', 'pca_factors')

Figures <- list() # accummulate all figures in this
SuppFigures <- list() # accumulate all supplementary figures in this
Legends <- list() # figure legend text
SuppLegends <- list() # supplementary figure legend text

fig_count <- 0
supFig_count <- 0
```

```{r import_lfs}
LFs <- import_LFs(TOOLS, inputDir)
```

```{r import_feature_weights}
FWs <- import_feature_weights(TOOLS, inputDir)
```


```{r}
plot_comp1 <- function(dt) {
  dt$method <- toupper(gsub("_factors", "", dt$method))
  comps <- lapply(setdiff(unique(dt$method), 'MAUI'), function(x) c('MAUI', x))
  ggboxplot(dt, 
          x = 'method', y = 'test_auc', color = 'method', 
          add = 'jitter', legend = 'none') + 
    stat_compare_means(method = 'wilcox.test', paired = T, 
                       method.args = list('alternative' = 'greater'), 
                     comparisons = comps) +
    labs(y = 'AUC') + theme(axis.text = element_text(size = 10))
}

plot_comp2 <- function(dt) {
  dt$method <- toupper(gsub("_factors", "", dt$method))
  dtc <- melt(dcast(dt, label ~ method, value.var = 'test_auc'), 
              id.vars = c('label', 'MAUI'))
  dtc$difference <- dtc$MAUI - dtc$value
  ggplot(dtc, 
         aes(x = MAUI, y = value)) + 
    geom_point() + geom_abline(slope = 1) + 
    facet_wrap(~ variable, nrow = 1) + 
    labs(y = 'AUC')
} 

get_top_by_label <- function(dt, label.type, topN = 5) {
  do.call(rbind, lapply(split(dt, dt[,get(label.type)]), function(x) {head(x, topN)}))
}

# find percent contribution of different datatypes to the top factor specific variables 
# LFs: Latent factors; nested list
# FWs: Feature weights for each LF; nested list 
# tool: pca/maui/mofa
# project: e.g. pancancer
# datatype: e.g. cnv_gex_mut
# factors: factor vector (e.g. cancer types for each sample or subtype info for each sample)
# top_lfs: top LF to pick per factor
# top_featuers: top features to pick per latent factor
plot_datatype_contribution_by_factor <- function(LFs, FWs, tool, project, datatype, 
                                                 factors, top_lfs = 1, top_features = 100) {
  experiment <- paste0(project, '.', datatype)
  L <- LFs[[tool]][[experiment]]
  W <- FWs[[tool]][[experiment]]
  dt <- get_factor_specific_variables(L, factors)
  top_vars <- get_top_by_label(dt[padj < 0.05][order(padj)], 'ref_cl', topN = top_lfs)
  # for each factor, pick top lfs and pick top features per lf and plot composition
  freq <- do.call(rbind, lapply(split(top_vars, top_vars$ref_cl), function(x) {
    l <- unique(x$variable) # one or more lfs 
    # get top features per lf and concatenate
    f <- do.call(c, lapply(l, function(y) {
      head(sort(abs(W[,y]), decreasing = T), top_features)
    }))
    freq <- data.table(table(sub("^(.+?)\\..+$", "\\1", unique(names(f)))))
    freq$factor <- unique(x$ref_cl)
    colnames(freq)[1] <- 'omics'
    return(freq)
  }))
  
  ggplot(freq, aes(x = factor, y = N)) + 
    geom_bar(stat = 'identity', aes(fill = omics), 
             position = 'fill') + coord_flip() + 
    labs(x = '', y = 'Percentage of top features contributing to top latent factors')
}
```

```{r pancancer_prediction, fig.height=9, fig.width=12}
# Find out if cancer types are predictable using latent factors 
res <- sapply(simplify = F, names(LFs), function(tool) {
  message(date(), " => ", tool)
  M <- LFs[[tool]]$pancancer.cnv_gex_meth_mut
  ct <- gsub("-", "_", surv[match(rownames(M), bcr_patient_barcode)]$project)
  res <- predict_labels_glmnet_multiclass(M, ct, partition = 0.6, nodes = 20)
})

pancancer_stats <- sapply(res, function(x) {
  caret::multiClassSummary(x, lev = levels(x$obs))
})

dt <- data.table(melt(pancancer_stats))[Var1 %in% c('Mean_Balanced_Accuracy')]
dt$Var2 <- toupper(gsub("_factors", "", dt$Var2))
p1 <- ggplot(dt, aes(x = Var2, y = value)) + 
  geom_bar(stat = 'identity', aes(fill = Var2)) + 
  labs(y = 'Mean Balanced Accuracy') + 
  theme(legend.title = element_blank(), axis.title.x = element_blank(), 
        axis.text = element_text(size = 14), axis.title = element_text(size = 16))

# performance visualisation
#m <- as.matrix(table(res$maui_factors$pred, res$maui_factors$obs))
#p2 <- pheatmap(apply(m, 1, function(x) round(x/sum(x) * 100, 1)), cluster_rows = F, cluster_cols = F, 
#         display_numbers = T, number_format = "%.1f", silent = T)

# plot cancer specific factors
M <- LFs$maui_factors$pancancer.cnv_gex_meth_mut
ct <- surv[match(rownames(M), bcr_patient_barcode)]$project

p2 <- plot_tsne(M, ct, show.labels = T) + 
  theme(legend.position = 'none')

p3 <- plot_label_specific_vars(M, ct)

# data type contribution to top LF per factor
p4 <- plot_datatype_contribution_by_factor(LFs, FWs, 'maui_factors', 
                                           'pancancer', 'cnv_gex_meth_mut', factors = ct, 
                                           top_lfs = 1, top_features = 100) 
p4 <- p4 + labs(y = 'Relative Contribution\nto top latent factor') + 
  theme(legend.position = 'top', legend.background = element_blank(), 
        legend.title = element_blank())

Fig <- plot_grid(plot_grid(p1, p2, nrow = 1, labels = c('A', 'B'),
                           rel_widths = c(1,2)), 
                  plot_grid(p4, p3, nrow = 1, labels = c('C', 'D'), 
                            rel_widths = c(1,2)), 
                  nrow = 2,
                  rel_heights = c(2,3))

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.pancancer_cancer_type_prediction.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(file.path(FigureFolder, fig.name),
              plot = Fig, units = 'in', width = 12, height = 12)
Legends[[fig_count]] <- "Predictive power of latent factors in distinguishing cancer types. A-B) comparing maui with PCA/MOFA/MCIA. AUC: Area under the ROC curve computed on the test dataset (30% of held-out data) trained on 70% of the dataset using a Random Forest model. Each point represents one cancer type (pairwise one-sided Wilcoxon test on AUCs, alternative = maui AUC is not greater than others) C) Adjusted Mutual Information (AMI) value computed by comparing unsupervised clustering labels (k-means algorithm, k set to 21) with the cancer types. D) Top maui LFs detected per cancer type. Size/color/opacity of the points represent the average neural activation value of the LF for the corresponding cancer type samples. E) Percentage of top feature types contributing to top predictive maui latent factor per cancer type."

```


```{r clustering_metrics, fig.width=10, fig.height=8}
# clustering metrics of various cancers 
# Use top 10 factors (derived from multi-omics) to cluster samples using cancer-specific LFs 

multi_omics_comb <- 'cnv_gex_meth_mut'
experiments <- grep(paste0('^TCGA-.*.', multi_omics_comb), names(LFs$pca_factors), value = T)
cl <- parallel::makeCluster(20)
parallel::clusterExport(cl, varlist = c('LFs', 'experiments', 'settings'))
cluster.stats <- do.call(rbind, sapply(simplify = F, names(LFs), function(tool) {
  message("Clustering top ",tool)
  stats <- do.call(rbind, pbapply::pbsapply(cl = cl, simplify = F, 
                                            intersect(names(LFs[[tool]]), experiments), 
                    function(experiment) {
    message(experiment)
    source(settings$utility_script)
    library(data.table)
    M <- LFs[[tool]][[experiment]]
    if(tool == 'maui_factors') {
      # to avoid highly correlated maui LFs to dominate clusters
      M <- scale(t(remove_redundant_variables(t(M))))
    } 
    # try topN from 5 to 25 (each tool may capture different amount of information 
    # by varying number of factors)
    stats <- do.call(rbind, lapply(seq(5, min(20, ncol(M)), 5), function(n) {
      message(n)
      M.sub <- t(subset_features_by_variance(t(M), topN = n))
      val <- c('internal') 
      if(ncol(M.sub) > 2) {val <- c('internal', 'stability')}
      res <- clValid::clValid(obj = M.sub,
                            nClust = 3:8,
                            clMethods = 'kmeans',
                            validation = val,
                            maxitems = 10000,
                            nstart = 1000, iter.max = 30)
      stats <- data.table::as.data.table(res@measures)[V1 %in% c('Silhouette', 'APN')]
      colnames(stats) <- c('metric', 'k', 'clustering_method', 'score')
      stats$top_factors <- n
      return(stats)
    }))
    stats$cancer_type <- strsplit(experiment, "\\.")[[1]][1]
    stats$datatypes <- strsplit(experiment, "\\.")[[1]][2]
    return(stats)
  }))
  stats$method <- tool
  return(stats)
}))
parallel::stopCluster(cl)

# plot silhouette/stability score comparison
dt1 <- cluster.stats[metric == 'Silhouette'][datatypes == multi_omics_comb,
                                             .SD[which.max(score)],
                                             by = c('cancer_type', 'method', 'k')]
dt1$method <- toupper(gsub("_factors", "", dt1$method))
comps <- lapply(setdiff(unique(dt1$method), 'MAUI'), function(x) c('MAUI', x))

p1 <- ggboxplot(dt1, 
          x = 'method', y = 'score', add = 'jitter', color = 'method') + 
  stat_compare_means(method = 'wilcox.test', paired = TRUE, 
                     comparisons = comps) + 
  labs(title = 'Silhouette score', x = '') + 
  theme(legend.position = 'none')


dt2 <- cluster.stats[metric == 'APN'][datatypes == multi_omics_comb,
                                             .SD[which.min(score)],
                                             by = c('cancer_type', 'method', 'k')]
dt2$method <- toupper(gsub("_factors", "", dt2$method))
comps <- lapply(setdiff(unique(dt2$method), 'MAUI'), function(x) c('MAUI', x))
p2 <- ggboxplot(dt2, 
          x = 'method', y = 'score', add = 'jitter', color = 'method') + 
  stat_compare_means(method = 'wilcox.test', paired = TRUE,  
                     comparisons = comps) + 
  labs(title = 'Cluster Stability Score (APN)', x = '') + 
  theme(legend.position = 'none')

# survival prediction accuracy benchmarking
# find survival-predictive LFs by fitting an initial RSF and use 
# top factors for a final model to compute Harrel's c-index
clin_factors <- c('age_at_initial_pathologic_diagnosis', 'gender', 'ajcc_pathologic_tumor_stage')
cl <- parallel::makeCluster(20)
parallel::clusterExport(cl, varlist = c('LFs', 'experiments', 'settings', 'surv', 'clin_factors'))
surv.stats <- do.call(rbind, sapply(simplify = F, names(LFs), function(tool) {
  message("survival benchmark for ",tool)
  do.call(rbind, pbapply::pbsapply(cl = cl, simplify = F, experiments, function(experiment) {
    message(experiment)
    source(settings$utility_script)
    require(data.table)
    require(survminer)
    M <- LFs[[tool]][[experiment]]
    clin <- process_clinical_covariates(rownames(M))
    clin <- subset(clin, select = intersect(colnames(clin), clin_factors))
    # compute pfi stats
    # fit a first model to filter variables 
    fit <- fit_RSF(surv, M, ntree = 500, 'PFI.time', 'PFI')
    # using a range of top variables, compute c index
    dt1 <- do.call(rbind, lapply(2:10, function(i) {
      vars <- names(head(sort(fit$importance, decreasing = T), i))
      rsf_stats <- fit_RSF_clin(get_surv_df(surv, clin, 'PFI', 'PFI.time'), 
                                M[,vars], ntree = 500)
      dt <- data.table('cindex.base' = rsf_stats$C_wo, 'cindex' = rsf_stats$C_with, 
                       'experiment' = experiment, 'method' = tool, 'topN' = i)
    }))
    dt1$endpoint <- 'PFI'
    # do the same for overall survival
    fit <- fit_RSF(surv, M, ntree = 500, 'OS.time', 'OS')
    dt2 <- do.call(rbind, lapply(2:10, function(i) {
      vars <- names(head(sort(fit$importance, decreasing = T), i))
      rsf_stats <- fit_RSF_clin(get_surv_df(surv, clin, 'OS', 'OS.time'), 
                                M[,vars], ntree = 500)
      dt <- data.table('cindex.base' = rsf_stats$C_wo, 'cindex' = rsf_stats$C_with, 
                       'experiment' = experiment, 'method' = tool, 'topN' = i)
    }))
    dt2$endpoint <- 'OS'
    return(rbind(dt1, dt2))
  }))
}))
parallel::stopCluster(cl)

dt <- surv.stats
dt$method <- toupper(gsub("_factors", "", dt$method))
dt$project <- unlist(sapply(strsplit(dt$experiment, "\\."), function(x) x[1]))
dt$endpoint <- ifelse(dt$endpoint == 'PFI', 'Progression Free Survival', 
                      'Overall Survival')
# get best performance per tool per project
dt <- dt[,.SD[which.max(cindex)], by = c('project', 'method', 'endpoint')]
# PCA/MOFA win, compare against PCA
comps <- lapply(setdiff(unique(dt$method), 'MAUI'), function(x) c('MAUI', x))
p4 <- ggboxplot(dt, x = 'method', y = 'cindex', color = 'method',
                add = 'jitter', facet.by = 'endpoint') +
  stat_compare_means(method = 'wilcox.test', paired = TRUE,
                     comparisons = comps) +
  labs(y = "Harrel's C-index", x = '') +
  theme(legend.position = 'none')

Fig <- plot_grid(plot_grid(p1, p2, labels = c('A', 'B'), nrow = 1),
                 p4, nrow = 2, labels = c('', 'C'))

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.cohort_based_metrics.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(file.path(FigureFolder, fig.name),        
       plot = Fig, units = 'in', 
       width = 10, height = 10)
Legends[[fig_count]] <- "Comparison of unsupervised clustering performances based on cluster homogeneity (Silhouette) in A) and cluster stability (Average Proportion of Non-Overlap (APN) in B). Each point represents a clustering score for 132 k-means clustering results (21 cancer types x for 6 different values of k from 3 to 8) based on the top 10 LFs/PCs derived from each tool. C) Same as in panels A and B), but split by the value of k used in clustering. D) Survival outcome prediction accuracy for 21 cancer types by each tool's top 10 survival-related factors based on Overall Survival or Progression Free Survival endpoints."
```


```{r survival_factors, fig.width=12, fig.height=8}
# survival-predictive factors
#I look for survival-predictive maui LFs, show how much c-index improves on top of 
#clinical factors (tumor stage/age/gender) and plot top survival-predictive factor per cancer.

# factors to use in the model
clin_factors <- c('age_at_initial_pathologic_diagnosis', 'gender', 'ajcc_pathologic_tumor_stage')
event <- 'PFI'
time <- 'PFI.time'

experiments <- grep('^TCGA-.*.cnv_gex_meth_mut', names(LFs$maui_factors), value = T)
cl <- parallel::makeCluster(20)
parallel::clusterExport(cl, varlist = c('LFs', 'clin_factors', 'event', 'time',
                                        'surv', 'experiments', 'settings'))
surv.stats <- pbapply::pbsapply(cl = cl, simplify = F, experiments, function(experiment) {
  require(data.table)
  require(survminer)
  require(survival)
  source(settings$utility_script)
  message(experiment)
  M <- LFs$maui_factors[[experiment]]
  # get clinical factors for the patients in matrix
  clin <- process_clinical_covariates(rownames(M))
  clin <- subset(clin, select = intersect(colnames(clin), clin_factors))
  # first filter variables by importance 
  fit <- fit_RSF(surv, M, 500, time, event)
  vars <- names(head(sort(fit$importance, decreasing = T), 5))
    
  # compute hazard ratios for the top factor
  v <- vars[1] 
  dat <- merge(clin, M[,v,drop = F], by = 'row.names')
  rownames(dat) <- dat$Row.names
  dat$Row.names <- NULL
  dat <- get_surv_df(surv, dat, event, time)
  # compute hazard ratios 
  cox1 <- coxph(Surv(time,status) ~ ., 
          data=dat, x = TRUE)
  hr <- data.frame(summary(cox1)[['conf.int']]) # get hazard ratios with conf intervals
  hr <- hr[grep(v, rownames(hr)), c(1,3,4)]
  colnames(hr) <- c('hr', 'hr_low', 'hr_high')
  rownames(hr) <- v
  p1 <- survminer::ggforest(cox1, data = dat)
    
  # split variable into high/low to compute survival adjusted curves
  cp <- find_survival_cutpoint(dat[,v,drop=F], surv, event_col = event, duration_col = time)
  dat[,v] <- ifelse(dat[,v] > cp, paste(v, 'high'), paste(v, 'low'))
  cox2 <- coxph(Surv(time,status) ~ ., 
                data=dat, x = TRUE)
  p2 <- survminer::ggadjustedcurves(fit = cox2, data = dat, variable = v, method = 'average')
  
  # compute Cindex with all survival-predictive LFs and without LFs 
  rsf_stats <- fit_RSF_clin(get_surv_df(surv, clin, event, time), 
                            M[,vars], ntree = 1000)
  
  return(list('p1' = p1, 'p2' = p2, 'hr' = hr, 
              'Cindex_base' = rsf_stats$C_wo, 'Cindex_with_LFs' = rsf_stats$C_with))
  
  return(NULL)
})
parallel::stopCluster(cl)

plots <- sapply(simplify = F, names(surv.stats), function(x) {   
  p <- surv.stats[[x]][['p2']] 
  if(!is.null(p)) { 
    p + theme(axis.text.x = element_text(size = 8), 
              axis.text.y = element_text(size = 8), 
              axis.title.x = element_blank(), 
              axis.title.y = element_blank(), 
              legend.title = element_blank(),
              legend.position = c(0.5, 0.9),
              legend.text = element_text(size = 8), 
              legend.background = element_blank(), 
              legend.direction = 'vertical') 
    }
})
plots <- plots[!sapply(plots, is.null)]
p1 <- cowplot::plot_grid(plotlist = plots, nrow = 3, 
                   labels = sapply(strsplit(names(plots), '\\.'), function(x) x[1]), 
                   label_size = 8)
# plot hazard ratios for top LF per cancer type 
hr <- do.call(rbind, lapply(names(surv.stats), function(x) {
  if(is.null(surv.stats[[x]])) {return(NULL)}
  message(x)
  df <- surv.stats[[x]][['hr']]
  df$project <- unlist(strsplit(x, '\\.'))[[1]]
  return(df)
}))
hr$latent_factor <- rownames(hr)
# remove hr with Inf values
hr <- hr[!is.infinite(hr$hr_high),]

p2 <- ggplot(hr, aes(x = reorder(paste0(project, ' (', latent_factor, ')'), hr), y = log(hr))) +
  geom_bar(stat = 'identity') + 
  geom_errorbar(aes(ymin = log(hr_low), ymax = log(hr_high)), width = 0.2) + 
  labs(x = '', y = 'log(hazard-ratio) of top latent factor per cancer\n(adjusted for tumor stage + age + gender)')+
  coord_flip()

# make a plot to show improvement in C index with LFs on top of clinical factors
ci <- do.call(rbind, lapply(names(surv.stats), function(x) {
  if(is.null(surv.stats[[x]])) {return(NULL)}
  df <- data.frame('base' = surv.stats[[x]][['Cindex_base']], 
                   'with_lf' = surv.stats[[x]][['Cindex_with_LFs']], 
                   'project' = unlist(strsplit(x, '\\.'))[[1]])
  return(df)
}))

dt <- melt(ci, id.vars = 'project')
dt$variable <- ifelse(dt$variable == 'base', 'Only clinical factors', 'Clinical factors + MAUI LFs')

p3 <- ggplot(ci, aes(x = reorder(project, with_lf))) + 
  geom_segment(aes(x = reorder(project, with_lf), xend = project, 
                   y = base, yend = with_lf)) + 
  geom_point(data = dt, aes(x = project, y = value, color = variable), size = 2) +
  coord_flip() + 
  labs(x = '', y = '') + 
  theme(legend.title = element_blank(), legend.position = 'bottom', 
        legend.background = element_blank(), 
        legend.margin = margin(), 
        legend.direction = 'vertical', legend.box.background = element_blank()) +
  scale_color_brewer(type = 'qual', palette = 6)

Fig <- cowplot::plot_grid(cowplot::plot_grid(p3, p2, nrow = 1, labels = c('A', 'B')),
                        p1, labels = c('', 'C'), nrow = 2)

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.surv.Cindex_improv.hazard_ratio.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       plot = Fig, width = 12, height = 14, units = 'in')
Legends[[fig_count]] <- "Using MAUI LFs for survival prediction. A) Harrell’s C-index computed using only clinical factors (tumor stage + age + gender) or using clinical factors along with survival-predictive MAUI LFs. B) Hazard ratios of top LFs picked for each cancer adjusted for clinical factors (tumor stage + age + gender). Kaplan-Meier survival curves adjusted for clinical factors (tumor stage + age + gender) stratified by the neural activation values of top survival-predictive LFs per cancer."
```


```{r clinical_factors, fig.width=12, fig.height=9}
# clinical factor associated MAUI LFs
# Find maui LFs associated to clinical factors and plot them

experiments <- grep('^TCGA-.*.cnv_gex_meth_mut', names(LFs$maui_factors), value = T)
# find clinical-factor associated LFs 
cl <- parallel::makeCluster(10)
parallel::clusterExport(cl, varlist = c('experiments', 'LFs', 'settings'))
clin.stats <- do.call(rbind, 
        pbapply::pbsapply(cl = cl, simplify = F, 
               experiments, function(experiment) {
               require(data.table)
               source(settings$utility_script)
               M <- LFs$maui_factors[[experiment]]
               clin <- process_clinical_covariates(rownames(M))
               dt <- do.call(rbind, 
                    pbapply::pbsapply(simplify = F, 
                                      colnames(clin), function(x) {
                      if(!is.numeric(clin[,x])) {
                        factors <- clin[,x]
                        m <- M[!is.na(factors),]
                        factors <- factors[!is.na(factors)]
                        dt <- get_factor_specific_variables(m, factors) 
                        dt$label <- x
                        return(dt)
                      }
                      return(NULL)
                      }))
               dt$project <- unlist(strsplit(experiment, "\\."))[[1]]
               return(dt)
             }))
parallel::stopCluster(cl)

# find top factors per project per label and plot
dt <- clin.stats[padj < 0.05, .SD[which.min(padj)],by = c('project', 'label')]

require(ggrepel)
dt$label <- stringr::str_wrap(gsub('_', ' ', dt$label), width = 8)
p1 <- ggplot(dt, aes(x = project, y = label)) + 
  geom_point(aes(color = -log10(padj), size = -log10(padj))) + 
  geom_text_repel(aes(label = variable)) + 
  coord_flip() +
  scale_color_gradient(low = 'blue', high = 'red') + 
  labs(x = '', y = 'clinical factor')

# pick example cases and show more detailed LF activation 
# top examples by clinical factor type
# top 5 variables per clinical factor 
top <- clin.stats[padj < 0.05,.SD[which.min(padj)], by = label][order(padj),.SD[which.min(padj)],by = project]
plots <- sapply(simplify = FALSE, 1:4, function(i) {
  pr <- top$project[i]
  l <- top$label[i]
  M <- LFs$maui_factors[[paste0(pr, '.cnv_gex_meth_mut')]]
  factors <- process_clinical_covariates(rownames(M))[[l]]
  M <- M[!is.na(factors),]
  factors <- factors[!is.na(factors)]
  plot_label_specific_vars(M, factors, string_width = 24)+ 
    labs(title = pr, subtitle = l) + 
    theme(legend.position = 'none')
})

p2 <- cowplot::plot_grid(plotlist = plots[1:2], nrow = 2, labels = c('B', 'C'))

Fig <- cowplot::plot_grid(p1, p2, rel_widths = c(3,2), labels = c('A'))

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.clinical_factors.LFs.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       plot = Fig, units = 'in', width = 12, height = 9)
Legends[[fig_count]] <- "A) Top significant (padj < 0.05) clinical factor-associated LFs per cancer type. B) Example case: top LFs associated with each histological subtype of TCGA-SARC. C) Example case: top LFs associated with each histological grade of TCGA-HNSC."
```

```{r msi_stats, fig.width=10, fig.height=8}
# Predicting MSI status using latent factors
# predict MSI status for pan-gastrointestinal tumors
# read MSI data
dataDir <- settings$GDCdataDir
MSI <- do.call(rbind, lapply(projectDict$`pan-gastrointestinal`, function(pr) {
  f <- file.path(dataDir, paste0(pr, '.MSI.tsv'))
  dt <- data.table::fread(f)[,c(2,4)]
  colnames(dt)[2] <- 'MSI'
  dt$project <- pr
  return(dt)
}))
# remove samples with undertermined MSI status
MSI <- MSI[MSI %in% c('MSI-H', 'MSI-L', 'MSS')]

dt <- do.call(rbind, lapply(names(LFs), function(tool) {
  M <- LFs[[tool]][['pan-gastrointestinal.cnv_gex_meth_mut']]
  y <- MSI[match(rownames(M), bcr_patient_barcode)]$MSI
  M <- M[!is.na(y),]
  y <- y[!is.na(y)]
  
  # find LFs predictive of MSI 
  dt <- get_factor_specific_variables(M, y)
  dt$tool <- tool
  return(dt)
}))

# compare top predictive factors across tools
dt$tool <- toupper(gsub("_factors", "", dt$tool))
p1 <- ggplot(dt[,.SD[which.min(padj)],by = c('ref_cl', 'tool')], 
       aes(x = ref_cl, y = -log10(padj))) + 
  geom_bar(stat = 'identity', aes(fill = tool), position = 'dodge') +
  geom_hline(yintercept = -log10(0.05)) + 
  coord_flip() + 
  theme(legend.title = element_blank(), axis.title.y = element_blank(), 
        plot.title = element_text(hjust = 0.5))

# focus on maui LFs to visualize MSI status-related LFs
M <- LFs$maui_factors[['pan-gastrointestinal.cnv_gex_meth_mut']]
y <- MSI[match(rownames(M), bcr_patient_barcode)]$MSI
M <- M[!is.na(y),]
y <- y[!is.na(y)]
top_vars <- unique(get_top_by_label(dt[tool=='MAUI'][padj < 0.05][order(padj)], 'ref_cl', 10)[['variable']])
df <- plot_tsne(M[,top_vars], y, returnData = T)
top_lf <- dt[order(padj)][ref_cl == 'MSI-H']$variable[1]
df <- merge(df, data.frame(M[,top_lf,drop =F]), by = 'row.names')
p2 <- ggplot(df, aes(x = tSNE1, y = tSNE2)) + 
    geom_point(aes(color = as.factor(group))) + 
    theme(legend.title = element_blank())
p3 <- ggplot(df, aes(x = tSNE1, y = tSNE2)) + 
    geom_point(aes_string(color = top_lf)) + 
    scale_color_gradient(low = 'gray', high = 'red')

p4 <- ggboxplot(df, x = 'group', y = top_lf, color = 'group', 
          add = 'jitter') + theme(legend.position = 'none', 
                                  axis.title.x = element_blank())

# plot a roc curve
rocs <- predict_cluster_labels_glmnet(M, y, returnROC = TRUE)
p5 <- plot_roc_list(rocs)

# top features that contribute to top factors relevant to MSI status prediction
f <- data.table::fread(file.path(inputDir, 'maui_factors', 
                               paste('pan-gastrointestinal', # project 
                                      'cnv_gex_meth_mut', #data type
                                      'maui_factors', # tool
                                      'feature_weights.csv', sep = '.')))
feat.M <- as.matrix(f[,-1])
rownames(feat.M) <- gsub('assay: ', '', f$V1)

# sort features by contribution to LF and plot by data type 
df <- data.frame(feat.M[,top_lf,drop = F])
df$data.type <- sub('^(.+?)\\..+$', '\\1', rownames(df))

# get top 100 features
df <- df[order(abs(df[,top_lf]), decreasing = T),]
freq <- do.call(rbind, lapply(0:29, function(i) {
  s <- (i*100+1)
  e <- (i+1)*100
  x <- data.frame(table(df[s:e,]$data.type))
  x$rank <- stringr::str_wrap(paste0("[",s,",",e,"]"),
                              width = 8)
  x$ind <- i
  return(x)
}))
p6 <- ggplot(freq[freq$ind < 5,], aes(x = reorder(rank, ind), y = Freq)) + 
  geom_bar(aes(fill = Var1), stat='identity') + 
  theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45)) + 
  labs(x = paste0("top features contributing to ",top_lf)) 
  

Fig <- cowplot::plot_grid(p1, p5, p2, p3, p4, p6,
                          nrow = 3, labels = 'AUTO')
fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.MSI.status.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       plot = Fig, units = 'in', width = 12, height = 12)
Legends[[fig_count]] <- "Predicting MSI status of pan-gastrointestinal tumors using MAUI latent factors. A) AUC values for predicting MSI status using MAUI LFs B) Top features that contribute to MAUI latent factor (‘LF95’) that is the most predictive latent factor in distinguishing samples with high microsatellite instability from the rest. C) tSNE plots of samples generated using top MSI-predictive LFs (5 LF per MSI class) colored by MSI status D) tSNE plots of samples colored by MAUI latent factor (‘LF95’) which is most predictive of MSI-H samples."
```

```{r}
# Analysis of non-small-cell lung cancer types (LUSC vs LUAD)
# reference study: https://www.nature.com/articles/s41598-020-77284-8
M <- LFs$maui_factors$nsclc.cnv_gex_meth_mut
M <- scale(M) #remove_redundant_variables(M, perc = 99)
ct <- surv[match(rownames(M), bcr_patient_barcode)]$project

# find type-specific LFs
dt <- get_factor_specific_variables(M, ct)
top_vars <- get_top_by_label(dt[padj < 0.05][order(padj)], 'ref_cl', 1)

# roc curves for predicting lung cancer types
rocs <- predict_cluster_labels_glmnet(M, ct, returnROC = TRUE)
aucs <- sapply(rocs, pROC::auc)
p1 <- pROC::ggroc(rocs, size = 1)
p1$data$name <- paste0(p1$data$name, " (AUC=", round(aucs[p1$data$name], 3),")")
p1 <- p1 + geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="grey", linetype="dashed") +
  theme(legend.title = element_blank(), legend.direction = 'vertical')

# tsne plot 
df <- plot_tsne(M, ct, returnData = T)

# top lf for LUSC
top_lf_lusc <- top_vars[ref_cl == 'TCGA-LUSC']$variable
top_lf_luad <- top_vars[ref_cl == 'TCGA-LUAD']$variable
df <- cbind(df, 
            M[,top_lf_lusc,drop = F],
            M[,top_lf_luad,drop = F])
p <- ggplot(df, aes(x = tSNE1, y = tSNE2)) 
p2 <- p + geom_point(aes(color = group)) + 
  geom_text_repel(data = get_centroid(df[,1:2], df$group), 
            aes(x,y,label = text.label), size = 5)
p3 <- p + geom_point(aes_string(color = top_lf_lusc)) + 
  scale_color_gradient(low = 'gray', high = 'red') +
  geom_text_repel(data = get_centroid(df[,1:2], df$group), 
            aes(x,y,label = text.label), size = 5)
p4 <- p + geom_point(aes_string(color = top_lf_luad)) + 
  scale_color_gradient(low = 'gray', high = 'red') +
  geom_text_repel(data = get_centroid(df[,1:2], df$group), 
            aes(x,y,label = text.label), size = 5)
p5 <- plot_datatype_contribution_by_factor(LFs, FWs, 'maui_factors', 'nsclc', 'cnv_gex_meth_mut', 
                                     factors = ct, top_lfs = 1, top_features = 500) + 
  labs(y = 'Relative Contribution\nto top latent factor')

dt <- data.table(M[,top_vars[['variable']]], keep.rownames = T)
dt <- dt[rowSums(dt[,2:3]) > 0] 
dt$pr <- surv[match(dt$rn, bcr_patient_barcode)]$project

# alternatively, split samples by LF scores, plot gene set scores 
scores <- import_geneset_scores(geneSetScoresFolder, annotation = 'cancersea')
S <- data.table(scores[intersect(rownames(scores), rownames(M)),], keep.rownames = T)

dt <- merge(dt, S, by = 'rn')

mdt <- melt(dt, measure.vars = setdiff(colnames(S), 'rn'))

p6 <- ggplot(mdt, aes(x = value, y = variable)) + 
  ggridges::geom_density_ridges(aes(fill = get(top_lf_lusc) > get(top_lf_luad)), alpha = 0.7) +
  labs(x = 'CancerSEA gene set scores', y = 'Cancer Cell States') + 
  guides(fill=guide_legend(title=paste0(top_lf_lusc, " > ",top_lf_luad)))

Fig <-  cowplot::plot_grid(p1, p2, p3, p4, p5, p6, 
                         labels = 'AUTO', ncol = 2)

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.luad_vs_lusc.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       Fig, units = 'in', 
       width = 10, height = 12)
Legends[[fig_count]] <- "Classification of Non-Small-Cell Lung Adenocarcinoma samples using MAUI latent factors.
A) ROC curves with AUC values on testing data (40% of the dataset) trained on Elastic Net with 5-fold cross-validation. B) t-SNE plot of MAUI LFs colored by cancer types. C) t-SNE plot of MAUI LFs colored by 
the top most-predictive latent factor for TCGA-LUSC samples. D) t-SNE plot of MAUI LFs colored by the top 
most predictive latent factor for TCGA-LUAD samples. E) Percentage of top 500 contributing features each of the top most predictive latent factors broken down into categories by cancer type and data type. F) Cancer Cell State score distribution of samples grouped by whether the sample has a higher score for LUSC-predictive latent factor than the LUAD-predictive latent factor."
```


```{r semi_supervised_subtypes, fig.width=10, fig.height=12}
# Semi-supervised clustering of samples 
# 1. Cluster samples by LFs associated to known TCGA subtypes or those that are associated to survival outcomes. 
#2. Annotate each cluster using cancer state scores or hallmark gene set scores 

## TCGA subtype informed clusters 
## Use-case: pan-gastrointestinal cancers
require(survminer)
require(cluster)
pr <- 'pan-gastrointestinal' 
experiment <- paste0(pr, '.cnv_gex_meth_mut')
M <- LFs$maui_factors[[experiment]]
M <- scale(M) #remove_redundant_variables(, perc = 99)
st <- tcga_subtypes[match(rownames(M), bcr_patient_barcode)]$Subtype_Selected
# find subtype specific LFs 
dt <- get_factor_specific_variables(M, st)

vars <- unique(get_top_by_label(dt[padj < 0.05][order(padj)], 'ref_cl', 3)[['variable']])

k <- length(na.omit(unique(st))) # set k to number of known subtypes
# cluster samples using only subtype specific factors 
clust <- data.frame(get_kmeans_subtypes(M[,vars], k_vals = k, min_cluster_size = 0))

# plots
df <- plot_tsne(M[,vars], as.factor(clust[,1]), returnData = T)
colnames(df)[3] <- 'maui'
df$tcga <- tcga_subtypes[match(rownames(df), bcr_patient_barcode)]$Subtype_Selected
df$cancertype <- surv[match(rownames(df), bcr_patient_barcode)]$project

p <- ggplot(df, aes(x = tSNE1, y = tSNE2))  
p1 <- p + geom_point(aes(color = maui)) +
  geom_text_repel(data = get_centroid(df[,1:2], df$maui), 
            aes(x,y,label = text.label), size = 6)
p2 <- p + geom_point(aes(color = tcga)) + 
        geom_text_repel(data = get_centroid(df[,1:2], df$tcga), 
            aes(x,y,label = text.label), size = 5)
p3 <- plot_survival(surv, df[,'maui',drop =F])[['plot']] + theme(legend.position = 'none') + labs(y = 'Progression Free Survival')
p4 <- plot_survival(surv, df[,'tcga',drop =F])[['plot']] + theme(legend.position = 'none') + labs(y = 'Progression Free Survival')

# use hallmark gene sets to annotate cluster specific functions
scores <- import_geneset_scores(geneSetScoresFolder, 'msigdb_hallmarks')

S <- scores[intersect(rownames(M), rownames(scores)),]
colnames(S) <- gsub("HALLMARK_", "", colnames(S))
clust$tcga <- tcga_subtypes[match(rownames(clust), bcr_patient_barcode)]$Subtype_Selected

# plot top gene sets
h1 <- plot_label_specific_vars(S, clust[rownames(S), 1], 
                              as_heatmap = T, cellwidth = 10, 
                              cellheight = 12,
                              top_vars_per_label = 2)
h2 <- plot_label_specific_vars(S, clust[rownames(S), 2], 
                              as_heatmap = T, cellwidth = 10, 
                              cellheight = 12, 
                              top_vars_per_label = 2)

# altogether
Fig <-  cowplot::plot_grid(p1, p2, p3, p4, h1$gtable, h2$gtable, 
                         labels = 'AUTO', ncol = 2)

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.semi_supervised.clustering.', experiment,'.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       Fig, units = 'in', 
       width = 10, height = 12)
Legends[[fig_count]] <- "Clustering of pan-gastrointestinal tumors guided by TCGA subtypes. Subtype specific MAUI LFs are used to cluster the samples, which yields better survival curves as shown in C,D). Clusters are annotated using pathway activity scores (top cluster associated cancer hallmarks)."
```

```{r semi_supervised_survival, fig.width=10, fig.height=12}

## Clustering informed by survival outcomes
## Pick survival-predictive LFs and cluster samples based on those

# factors to use in the model
clin_factors <- c('age_at_initial_pathologic_diagnosis', 'gender', 'ajcc_pathologic_tumor_stage')

experiments <- grep('^TCGA-.*.cnv_gex_meth_mut', names(LFs$maui_factors), value = T)
cl <- parallel::makeCluster(10)
parallel::clusterExport(cl, varlist = c('LFs', 'clin_factors', 'surv', 
                                        'experiments', 'settings'))
prog.clust <- pbapply::pbsapply(cl = cl, simplify = F, experiments, 
                                function(experiment){
    require(data.table)
    require(survminer)
    source(settings$utility_script)
    message(experiment)
    M <- LFs$maui_factors[[experiment]]
    # get clinical factors for the patients in matrix
    clin <- process_clinical_covariates(rownames(M))
    clin <- subset(clin, select = intersect(colnames(clin), clin_factors))
    
    fit <- fit_RSF(surv, M, duration_col = 'PFI.time', event_col = 'PFI')
    prog_lfs <- names(head(sort(fit$importance, decreasing = T), 5))
    # now cluster samples based on only survival predictive factors
    clust <-  get_kmeans_subtypes(M[,prog_lfs], k_vals = 3:8, min_cluster_size = 0)
    # find value of k which minimizes log-rank p-value
    dt <- do.call(rbind, lapply(colnames(clust), function(x) {
      message(x)
      pval <- plot_survival(surv, clust[,x,drop=F], return_pval = T)
      data.table('k' = x, 'pval' = pval)
    }))
    
    # return clustering with best result
    top <- dt[order(pval)][1]$k
    return(list('prog.lf' = M[,prog_lfs], 'prog.clust' = clust[,top,drop = F]))
})
parallel::stopCluster(cl)

# compare maui prognostic clusters with TCGA labels 
stats <- do.call(rbind, lapply(names(prog.clust), function(experiment) {
  message(experiment)
  if(is.null(prog.clust[[experiment]])) {return(NULL)}
  df <- data.frame(prog.clust[[experiment]][['prog.clust']])
  colnames(df)[1] <- 'maui'
  df$tcga <- tcga_subtypes[match(rownames(df), bcr_patient_barcode)]$Subtype_Selected
  do.call(rbind, lapply(colnames(df), function(x) {
    if(length(unique(df[,x])) < 2) {
      pval <- NA
    } else {
      pval <- plot_survival(surv, df[,x,drop = F], return_pval = T)
    }
    return(data.table('source' = x, 'pval' = pval, 'experiment' = experiment))
  }))
}))

stats$cancertype <- gsub('.cnv_gex_meth_mut', '', stats$experiment)
# which cancers can we improve upon tcga?
p1 <- ggplot(stats, aes(x = cancertype, y = -log10(pval))) +  
  geom_bar(stat = 'identity', aes(fill = source), position = 'dodge') +
  geom_hline(yintercept = -log10(0.05)) + 
  coord_flip() + 
  scale_fill_brewer(type = 'qual', palette = 6) 

# use canonical pathways to annotate prognostic groups
scores <- import_geneset_scores(geneSetScoresFolder, 'msigdb_canonical_pathways')

# scores: geneset scores
# M: survival predictive LF matrix
# maui_clust: best survival prognostic clustering of M 
plot_clusts <- function(surv, M, maui_clust, scores) {
  df <- plot_tsne(M, as.factor(maui_clust[,1]), returnData = T)
  colnames(df)[3] <- 'maui'

  message("running plot clusts")
  message("p1")
  p1 <- ggplot(df, aes(x = tSNE1, y = tSNE2)) + 
    geom_point(aes(color = maui)) +
    geom_text_repel(data = get_centroid(df[,1:2], df$maui), 
            aes(x,y,label = text.label), size = 6)
  # plot survival for the worst prognostic group, and the rest
  ms <- get_median_survival_by_group(surv, df[,'maui',drop=F])

  # find clusters with worst/best prognosis (by median survival)
  worst <- names(sort(ms)[1])
  best <- names(sort(ms, T)[1])
  
  message("p2")
  p2 <- plot_survival(surv, 
                      df[df$maui %in% c(best, worst), 
                         'maui', drop = F])[['plot']] +
    labs(y = 'PFI') +
    theme(legend.position = 'left', legend.title = element_blank()) + 
    scale_color_brewer(type = 'qual', palette = 6)
  
  # heatmap of hallmark scores for best/worst survivors
  selected <- intersect(rownames(df[df$maui %in% c(worst, best),]), rownames(S))
  dt <- get_factor_specific_variables(S[selected,], df[selected, 'maui'])
  # select factors 
  dt[padj < 0.05][order(padj)]
  message("h1")

  h1 <- plot_label_specific_vars(S[selected,], 
                                 df[selected, 'maui'], 
                                 padj_threshold = 0.1,
                                as_heatmap = T, cellwidth = 15, 
                                top_vars_per_label = 5, cellheight = 15)
  return(list('p1' = p1, 'p2' = p2, 'h1' = h1))
}

# plot examples for which we improve upon tcga
dt <- data.table(dcast(stats, experiment ~ source, value.var = 'pval'))
dt$improvement <- -log10(dt$maui) - -log10(dt$tcga)
dt <- dt[order(improvement, decreasing = T)]

e <- dt[1,]$experiment
M <- prog.clust[[e]]$prog.lf
maui_clust <- prog.clust[[e]]$prog.clust
S <- scores[intersect(rownames(M), rownames(scores)),]
P <- plot_clusts(surv, M, maui_clust, S)

Fig <- cowplot::plot_grid(p1, plot_grid(P$p1, P$p2, nrow = 1, labels = c('B', 'C')), 
                   P$h1$gtable, nrow = 3, labels = c('A', '', 'D'))

message("Got the figure")

fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.semi_supervised.prognostic.clustering.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       plot = Fig, units = 'in', 
       width = 10, height = 12)
Legends[[fig_count]] <- "Log-rank test of prognostic subtypes by MAUI and existing TCGA subtypes. B) tSNE plot of MAUI LFs that are predictive of survival outcomes for TCGA-UCEC. C) Kaplan-Meier curve of the best/worst surviving prognostic MAUI clusters D) Biological pathway scores that distinguish best/worst surviving clusters."
```


```{r}
# Show subtypes depend on the objective (dependent variable) - they are dynamic, not universal or carved in stone 
# for a given cancer. There is not just one set of subtypes for a given cancer. Subtypes need to be phrased 
# along with the dependent variable used to come up with the subtypes. 
# Patients clustering depend on the objective of stratification
clin_factors <- c('age_at_initial_pathologic_diagnosis', 'gender', 'ajcc_pathologic_tumor_stage')
project <- 'pan-gastrointestinal'
datatype <- 'cnv_gex_meth_mut'
experiment <- paste0(project, '.', datatype)

M <- LFs$maui_factors[[experiment]]
clin <- process_clinical_covariates(rownames(M))
clin <- subset(clin, select = intersect(colnames(clin), clin_factors))

pfi_vars <- get_prognostic_covariates(surv, clin, M, event_col = 'PFI', duration_col = 'PFI.time')
pfi_clust <- get_kmeans_subtypes(M[,unique(pfi_vars$variable)], k_vals = 3:8, min_cluster_size = 0)
pfi_k <- names(which.min(sapply(colnames(pfi_clust), function(x) plot_survival(surv, pfi_clust[,x,drop = F], 'PFI.time', 'PFI', T))))

os_vars <- get_prognostic_covariates(surv, clin, M, event_col = 'OS', duration_col = 'OS.time')
os_clust <- get_kmeans_subtypes(M[,unique(os_vars$variable)], k_vals = 3:8, min_cluster_size = 0)
os_k <- names(which.min(sapply(colnames(os_clust), function(x) plot_survival(surv, os_clust[,x,drop = F], 
                                                                             'OS.time', 'OS', T))))

# combine with known pan-gi subtype annotation
df <- merge(pfi_clust[,pfi_k,drop = F], os_clust[,os_k,drop = F], by = 'row.names')
df$subtype <- tcga_subtypes[match(df$Row.names, bcr_patient_barcode)]$Subtype_Selected
df[is.na(df$subtype),]$subtype <- 'Unavailable'
df$msi <- MSI[match(df$Row.names, bcr_patient_barcode)]$MSI
df[is.na(df$msi),]$msi <- 'Unavailable'
rownames(df) <- df$Row.names
df$Row.names <- NULL
colnames(df) <- c('Overall Survival', 'Progression Free Survival', 'Molecular Subtype', 'MSI Status')
df <- data.frame(apply(df, 2, as.factor), check.names = F)
df <- df[order(df[,1]),]
m <- apply(df, 2, function(x) as.numeric(as.factor(x)))
rownames(m) <- rownames(df)

colors <- structure(1:7, names = c("1", "2", "3", "4", "5", "6", "7"))
p1 <- Heatmap(t(m), name = "cluster", col = colors, cluster_rows = F, cluster_columns = F,
              show_column_names = F, row_names_side = 'left',
              column_title = 'Pan-gastrointestinal Cancer Samples\n(ordered by Overall Survival Clusters)')
p1 <- grid::grid.grabExpr(ComplexHeatmap::draw(p1))
# compute pairwise AMI 
ami <- sapply(colnames(df), function(x) {
  sapply(colnames(df), function(y) {
    df <- df[!is.na(df[,x]) & !is.na(df[,y]),]
    aricode::AMI(df[,x], df[,y])
  })
})

p2 <- ggcorrplot::ggcorrplot(ami, legend.title = 'AMI', lab = T, type = 'lower', outline.color = 'white') +
  scale_fill_gradient(limits = c(0,1), low = 'white', high = 'red') + 
  guides(fill=guide_legend(title='AMI'))

bipartite_plots <- unlist(lapply(1:(ncol(df)-1), function(i) {
  lapply((i+1):ncol(df), function(j) {
    p <- plot_cluster_comparison(df[,i,drop = F], df[,j,drop = F]) + 
      theme(plot.margin = unit(c(0.2, 1.5, 0, 1.5), units = 'in'))
  })
}), recursive = F)


Fig <- cowplot::plot_grid(p1, p2, labels = 'AUTO', nrow = 2)
supFig_count <- supFig_count + 1
SuppFigures[[supFig_count]] <- Fig
fig.name <- paste0('SuppFigure', supFig_count, '.subtype_dependency.pdf')
names(SuppFigures)[supFig_count] <- fig.name
ggsave(file.path(FigureFolder, fig.name), 
              plot = Fig, units = 'in', width = 18, height = 12)
SuppLegends[[supFig_count]] <- "Demonstration of how cancer subtypes are context/objective dependent.
A) Heatmap of patient cluster memberships based on different objectives: optimum stratification based on overall survival or progression free survival, molecular homogeneity (TCGA pan-GI subtypes), or micro-satellite instability (MSI) status. Columns are ordered first by membership in the optimum Overall Survival cluster membership. B) Pairwise Adjusted Mutual Information (AMI) of cluster labels obtained via different patient stratification methods. The AMI value ranges from 0 to 1 and the higher the value, the more overlap between patient partitions."

Fig <- cowplot::plot_grid(plotlist = bipartite_plots, nrow = 3, labels = 'AUTO')
supFig_count <- supFig_count + 1
SuppFigures[[supFig_count]] <- Fig
fig.name <- paste0('SuppFigure', supFig_count, '.subtype_dependency.bipartite_plots.pdf')
names(SuppFigures)[supFig_count] <- fig.name
ggsave(file.path(FigureFolder, fig.name), 
              plot = Fig, units = 'in', width = 14, height = 14)
SuppLegends[[supFig_count]] <- "Demonstration of how cancer subtypes are context/objective dependent"
```


```{r immunotherapy_response}
# immunotherapy response prediction analysis: 
# TODO: pass paths via args
settings_imtrp <- yaml::read_yaml('/data/local/buyar/arcas/pancancer_multiomics_manuscript/results/immunotherapy_response/Mariathasan_et_al/settings.yaml')
pathways <- readRDS('/data/local/buyar/arcas/subtyping_paper/data/GeneSets/msigdb.pathways.RDS')  

LFs_imtrp <- import_LFs(c('maui_factors', 'mofa_factors', 'pca_factors'), settings_imtrp$pipeline_output)
FWs_imtrp <- import_feature_weights(c('maui_factors'), settings_imtrp$pipeline_output)
colData <- data.table::fread(settings_imtrp$clin)
colnames(colData)[1] <- 'bcr_patient_barcode'

dt <- do.call(rbind, lapply(names(LFs_imtrp), function(tool) {
  M <- LFs_imtrp[[tool]]$mariathasan.gex
  # find LFs predictive of response to therapy 
  dt <- get_factor_specific_variables(M, colData$binaryResponse)[order(padj)]
  #dt <- compute_anova(M, colData$binaryResponse)
  dt$tool <- tool
  return(dt)
}))

dt[,.SD[which.min(padj)],by = c('tool', 'ref_cl')]
dt$tool <- toupper(gsub("_factors", "", dt$tool))
dt$ref_cl <- ifelse(dt$ref_cl == 'CR/PR', 'Responders', 'Non-responders')

p1 <- ggplot(dt[,.SD[which.min(padj)],by = c('tool', 'ref_cl')], 
       aes(x = ref_cl, y = -log10(padj))) + 
  geom_bar(stat = 'identity', aes(fill = tool), position = 'dodge') +
  geom_hline(yintercept = -log10(0.05)) + 
  coord_flip() + 
  theme(legend.title = element_blank(), axis.title.y = element_blank(), 
        plot.title = element_text(hjust = 0.5))

# heatmap of top vars 
# plot maui factors for responders/non-responders
M <- LFs_imtrp$maui_factors$mariathasan.gex
top_vars <- unique(dt[tool == 'MAUI'][padj < 0.01]$variable)
m <- M[,top_vars]
f <- ifelse(colData$binaryResponse == 'CR/PR', 'Responders', 'Non-responders')
m <- m[!is.na(f),]
f <- f[!is.na(f)]
p2 <- pheatmap::pheatmap(get_basis_matrix(m[,top_vars], f), silent = T)

# survival stratification using the top LF 
require(survminer)
require(survival)
top_lf <- dt[order(padj)][ref_cl == 'Responders'][1,]$variable
cp <- find_survival_cutpoint(m[,top_lf,drop = F], colData, event_col = 'censOS', duration_col = 'os')
p3 <- plot_survival(surv = colData, 
                    partition.df = data.frame('group' = ifelse(m[,top_lf] > cp, 
                                              paste0(top_lf, ">", round(cp, 1)),
                                              paste0(top_lf, "<=", round(cp, 1))), 
                                              row.names = rownames(m)), 
                    duration_col = 'os', event_col = 'censOS') 

# top go terms for top features of top LF 
W <- FWs_imtrp$maui_factors$mariathasan.gex
feats <- data.table(W[,top_lf,drop=F], keep.rownames = T)[order(abs(get(top_lf)), decreasing = T)][1:100]
# top pathways for top lf
top_terms <- compute_geneset_enrichment(feats$rn, pathways)[order(pval)][padj < 0.05][1:5]
top_terms$term_wr <- stringr::str_wrap(gsub("_", " ", top_terms$term), width = 24)
p4 <- ggplot(top_terms, aes(x = reorder(term_wr, -pval), y = -log10(padj))) + 
  geom_bar(stat = 'identity') + 
  coord_flip() + labs(x = '') 
colnames(feats)[2] <- 'top_lf'
p5 <- ggplot(feats[1:10,], aes(x = reorder(rn, abs(top_lf)), y = abs(top_lf))) + 
  geom_bar(stat = 'identity') + coord_flip() + labs(x = '', y = 'Feature Importance (absolute)')

# correlation of top LF with tumor mutation burden
# get samples with both response and tmb annotation
dt <- do.call(rbind, lapply(names(LFs_imtrp), function(tool) {
  M <- LFs_imtrp[[tool]]$mariathasan.gex
  dt <- data.table(cor(M, colData$`Neoantigen burden per MB`, use = 'complete.obs'),
                   keep.rownames = T)
  dt$tool <- tool
  return(dt)
}))
dt <- dt[,.SD[which.max(abs(V1))], by = c('tool')]
dt$tool <- toupper(gsub("_factors", "", dt$tool))
p6 <- ggplot(dt, aes(x = tool, y = abs(V1))) + 
  geom_bar(stat = 'identity', aes(fill = tool), position = 'dodge') +
  coord_flip() + 
  labs(y = 'Correlation with Tumor Mutation Burden') + 
  theme(legend.title = element_blank(), axis.title.y = element_blank(), 
        plot.title = element_text(hjust = 0.5)) 
# immune phenotypes 
dt <- do.call(rbind, lapply(names(LFs_imtrp), function(tool) {
  M <- LFs_imtrp[[tool]]$mariathasan.gex
  # find LFs predictive of immune phenotypes 
  dt <- get_factor_specific_variables(M, colData$`Immune phenotype`)[order(padj)]
  dt$tool <- tool
  return(dt)
}))

dt[,.SD[which.min(padj)],by = c('ref_cl', 'tool')]
dt$tool <- toupper(gsub("_factors", "", dt$tool))
p7 <- ggplot(dt[,.SD[which.min(padj)],by = c('ref_cl', 'tool')], 
             aes(x = ref_cl, y = -log10(padj))) + 
  geom_bar(stat = 'identity', aes(fill = tool), position = 'dodge') +
  geom_hline(yintercept = -log10(0.05)) + 
  labs(x = 'Tumor Immune Phenotypes') + 
  coord_flip() + 
  theme(legend.title = element_blank(), axis.title.y = element_blank(), 
        plot.title = element_text(hjust = 0.5)) 

Fig <- cowplot::plot_grid(
  cowplot::plot_grid(p1, p6, p7, nrow = 1, labels = 'AUTO'),
  cowplot::plot_grid(p2$gtable, p3$plot, p4, p5, nrow = 2, labels = c('D', 'E', 'F', 'G')),
  nrow = 2, 
  rel_heights = c(1,2)
  ) 
fig_count <- fig_count + 1
Figures[[fig_count]] <- Fig
fig.name <- paste0('Figure', fig_count, '.immunotherapy_response.pdf')
names(Figures)[fig_count] <- fig.name
ggsave(filename = file.path(FigureFolder, fig.name), 
       plot = Fig, units = 'in', 
       width = 12, height = 14)
Legends[[fig_count]] <- "Predicting responders to anti-PD-L1 treatment in a cohort of Metastatic Urothelial
Cancers (N=348) using MAUI. A) AUC curve for predicting Complete/Partial Responders (CR/PR) to the anti-PD-L1
treatment using an Elastic Net Model on a subset of MAUI latent factors individually predictive of treatment response groups. B) Average activation score of top latent factors predictive of treatment response groups. C) Top pathways enriched among top 100 genes that contribute to the top latent factor (LF44). D) Survival stratification of the 
cohort based activation score of LF44 (high = LF44 > 1.4, low = LF44 < 1.4). E) Top 10 genes contributing to LF44
F) Correlation between LF44 activation score and the tumor (neo-antigen) mutation burden"
```


```{r print_figures, results='asis', include=TRUE, fig.width=10, fig.height=11}
base_url <- 'https://bimsbstatic.mdc-berlin.de'
for(i in 1:length(Figures)) {
  fig.url <- gsub("/data/bimsbstatic/public", base_url, file.path(FigureFolder, names(Figures)[i]))
  cat("# Figure",i,"[high-res image](",fig.url,")\n\n")
  print(Figures[[i]])
  cat("\n\n Figure",i,":",Legends[[i]],"\n\n")
}

for(i in 1:length(SuppFigures)) {
  fig.url <- gsub("/data/bimsbstatic/public", base_url, file.path(FigureFolder, names(SuppFigures)[i]))
  cat("# Supplementary Figure",i,"[high-res image](",fig.url,")\n\n")
  print(SuppFigures[[i]])
  cat("\n\n Supplementary Figure",i,":",SuppLegends[[i]],"\n\n")
}
```

`r date()`
